### ISSUE TITLE
The View Task becomes empty after i restart the App

### ISSUE THREAD

**Issue by sidddhchhabra** [Algorithmics001/Hackathon#31]
I added a few tasks in "Add Task" option. When i tried to view them in "View Task" they were there. But if i close the app and restart it. The view task becomes empty.

**Comment by Algorithmics001** [comment]
This was happening because the reset function that creates json files (which have all the task data) was being called every time you opened the app. The issue has been fixed not the function will be called only when you grant the permission to use storage.
